blank_issues_enabled: false

contact_links:
  - name: Game compatibility list
    url: https://github.com/cameronbosch/quackstation
    about: Please refer to the game compatibility list before opening an issue.
